highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://bdrown.github.io/vitae
author: Bryon Drown

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Bryon Drown's CV
name: Bryon Drown
email: bryon.drown@gmail.com
email_full: mailto:bryon.drown@gmail.com
website: github.io/intro
website_full: https://bdrown.github.io/intro
github: bdrown
twitter: BryonDrown
tel: 774-219-4068
tel_full: tel:7742194068
google_maps: 'https://goo.gl/maps/vpY4ZcV1pU91PPWy5'
address:
  street: 1040 Ashland Ave.
  postcode: 60202
  city: Evanston, IL
  country: United States
google_analytics: UA-146199436-1

# needed for travis-ci build
exclude: [vendor]
